### PR TITLE
chore(head): add auto redirect

### PR DESCRIPTION
**Pull request by AugustinMauroy**

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Under js.org rules, automatic redirects away from js.org are not permitted.

**Comment by AugustinMauroy** [comment]
So what we can do

**Comment by MattIPv4** [comment]
Probably best to leave it as it is, with the link that folks can click -- if an automatic redirect gets added, the cleanup logic run on js.org's end will remove the subdomain.

Maybe the design could do with an update though if that's a concern?

**Comment by AugustinMauroy** [comment]
> Maybe the design could do with an update though if that's a concern?

Why not

**Comment by Trott** [comment]
Doing much of anything with node.js.org is (IMO) low-value work. I would leave it as it is. But if someone wants to do a little bit of a redesign on it to make it align more with our current design and content, that's fine. But it's also completely fine to leave it as it is. I doubt the site gets much traffic at all, and if it does, then it's doing the right thing by pointing users to the canonical site.

**Pull request closed without merging**
