### PR TITLE
Created robots.txt

### LINKED ISSUE #2: SEO issues
Could having this site open to crawlers pose potential issues in clashes with the main site (nodejs.org)?

Would it be worth creating a robots.txt file that denies all crawlers, as well as adding no-index meta tags to both pages to ensure that neither page gets indexed?

### PR DESCRIPTION
**Pull request by raftar2097**
"Resolves #2"
The “User-agent: *” part means that it applies to all robots. The “Disallow: /” part means that it applies to your entire website.
In effect, this will tell all robots and web crawlers that they are not allowed to access or crawl your site.
Disallowing all robots on a live website can lead to your site being removed from search engines and can result in a loss of traffic and revenue

### CODE REVIEW

**Comment by raftar2097** [comment]
cc @MattIPv4  done

**Comment by MattIPv4** [comment]
Thanks. Please close #5 if you are using this PR.

**Comment by raftar2097** [comment]
cc @MattIPv4  closed #5

**Review by MattIPv4 — APPROVED** [review]
Lgtm.

**Comment by Trott** [comment]
Assuming this works at keeping the repo out of search engines, wouldn't it mean that the issue tracker (for example) wouldn't show up in search engine results? I don't think that's what we want, is it?

(It's not clear to me that having the repo in search results has caused significant problems, but I also don't exactly pay attention to every issue opened etc. so maybe it as?)

**Comment by MattIPv4** [comment]
This will keep https://node.js.org out of search engines, so there is no cross-talk with https://nodejs.org

Shouldn't affect issue trackers or repos at all.

**Comment by Trott** [comment]
Oooooohhhhhh....Now it's all making sense. Thanks!

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
Thanks for the pull request!

**Comment by MattIPv4** [comment]
Ty!

**Comment by Trott** [comment]
> Oooooohhhhhh....Now it's all making sense. Thanks!

I initially missed the second `.` in the repo name and thought this was for `nodejs.org` and was all "What? This can't be what I think?" 😀

**Pull request merged**
